openapi: 3.1.0
info:
  title: Система сертификации драгоценных камней
  description: |-
    Ключевая функциональность представляемая системой:
    - Учет договоров и заявок на сертификацию и сертификационных документов.
    - Сертификация драгоценных камней.
    - Выпуск сертификационных документов на драгоценные камни.
    - Проверка подлинности сертификатов
  version: 0.0.1

tags:
  - name: Приемка
    description: |-
      Процесс, включающий в себя: взвешивание камней, печать и подписание Клиентом пакета входных документов, 
      регистрацию приемщиком входящей партии. 

paths:
  /acceptance/registerLot:
    post:
      tags:
        - Приемка
      summary: Регистрация нового лота
      description: |-
        Пользователь регистрирует новый входящий лот. 
        Результат: в системе появился экземпляр сущности "Входящий лот", ассоциированный с клиентом, заявкой или доп.соглашением; обладающий уникальным номером, количеством камней, весом камней.
      operationId: registerLot
      requestBody:
        description: Команда регистрации лота
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerLotCommand'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/registerLotResponse'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
  /acceptance/registerPackage:
    post:
      tags:
        - Приемка
      summary: Регистрация пакета
      description: |-
        Пользователь регистрирует пакеты внутри лота.
        Результат: в системе появился экземпляр сущности "Пакет", ассоциированный с входящим лотом; обладающий уникальным номером, весом, признаком системы оценки
      operationId: registerPackage
      requestBody:
        description: Команда регистрации пакета
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/registerPackageCommand'
        required: true
      responses:
        '201':
          description: Operation accepted


components:
  schemas:
    registerLotCommand:  
      type: object
      description: |- 
        Команда регистрации входящего лота
      properties:
        method:
          type: string
          enum: 
            - acceptance:register-lot
        clientId:
          type: integer
          format: int32
          description: Идентификатор клиента
        requestId:
          type: integer
          format: int32
          description: Номер заявки или доп. соглашения

    registerPackageCommand:  
      type: object
      description: |- 
        Команда регистрации пакета
      properties:
        method:
          type: string
          enum: 
            - acceptance:register-package
        certificationType:
          type: object
          description: Система сертификации
        packageType:
          type: object
          description: Тип пакета

    registerLotResponse:  
      type: object
      description: |- 
        todo
        
    Lot:
      type: object
      description: |- 
        Входящий лот — совокупность камней или ювелирных изделий, пришедших от клиента для проведения сертификации. 
        Входящий лот отражается в Дополнительном соглашении или Заявке. 
        Один входящий лот – одна заявка или доп.соглашение.
      properties:
        lotNumber:
          type: integer
          format: int64
          description: Номер лота, уникален, формируется системой при регистрации лота
          example: 
            - 123456
        date:
          type: string
          format: date-time
          description: Дата прихода, вводится приемщиком вручную при регистрации лота
          example: "2024-05-28T12:20:50.52Z"
        clientId:
          type: integer
          format: int32
          description: Идентификатор клиента, клиент выбирается приемщиком при регистрации лота.
          example: 
            - 198772
        state:
          type: string
          description: Статус лота. Новый - после регистрации лота. В работе - после того как хотя бы 1 пакет лота будет направлен в работу. Закрыт - после того как лот закроют. 
          enum:
            - "Новый"
            - "В работе"
            - "Закрыт"
        requestId:
          type: string
          description: Номер заявки или доп. соглашения, вводится приемщиком вручную (пока что) при регистрации лота
          example: 
            - "562/2024"
    Package:
      type: object
      description: |-
        Пакет — конверт, содержащий объект сертификации. Является составной частью входящего лота. Может включать:
         - одиночный драгоценный камень
         - партия драгоценных камней
         - ювелирное изделие
      properties:
        packageNumber:
          type: integer
          format: int64
          description: Номер пакета, уникальный, формируется системой. В будущем номер должен будет переноситься на QR или штрих-код для нанесения на физический пакет.
          example:
            - 123456
        certificationType:
          type: string
          description: Система сертификации, выбирает приемщик при регистрации пакета.
          enum:
            - Сертификация по РФ системе
            - Сертификация по РФ системе + по международной системе
        packageType:
          type: string
          description: Тип пакета, выбирает приемщик при регистрации пакета.
          enum:
            - одиночный драгоценный камень
            - партия драгоценных камней
            - ювелирное изделие
        state:
          type: string
          description: Статус пакета
          enum:
             - Новый
             - В работе
             - Закрыт
        certificate:
          $ref: '#/components/schemas/Certificate'
        worksheet:
          $ref: '#/components/schemas/Worksheet'
    Certificate:
      type: object
      description: |- 
        Сертификационный документ	— документ, подтверждающий характеристики драгоценного камня или ювелирного изделия, прошедшего сертификацию.
        Бывает трех видов: Сертификат соответствия, Экспертное заключение, Аттестат. 
      properties:
        type:
          type: string
          description: Тип документа, при печати документа приемщик (или другой пользователь, кот-ый печатает) должен выбрать соответствующий шаблон. В будущем система должна будет подбирать нужный вид. 1. Сертификат соответствия выдается только на бриллианты натурального происхождения или ограненные алмазы лабораторного происхождения. А также на партии указанных камней. Может содержать изображение плоттинга (опционально).2.Экспертное заключение выдается на драгоценные камни, отличные от п.1. Содержит фото образца. 3. Аттестат выдается только на ювелирное изделие. Содержит фото образца.
          enum:
            - Сертификат соответствия
            - Экспертное заключение
            - Аттестат ювелирного изделия
        number:
          type: integer
          format: int64
          description: Номер документа. Вводится приемщиком при распечатке. Нужно проверять на уникальность. В будущем планируется сделать регистрацию сертификата в системе через сканирование кода.
          example: 20000000123456
        date:
          type: string
          format: date
          description: Дата выдачи документа. Вводит работник приемщик (или другой пользователь, кот-ый печатает) при печати
          example: "2024-05-28"
    Worksheet:
      type: object
      description: |- 
        Рабочий лист — форма, в которую вводятся результаты диагностики (натуральность, форма, цвет, чистота и др.характеристики камня). 
        Лист создается для каждого пакета в лоте.
      properties:
        number:
          type: integer
          format: int64
          description: Номер рабочего листа, формируется системой при передаче пакета в работу
        startDate:
          type: string
          format: date-time
          description: Дата передачи в работу
          example: "2024-05-28T12:20:50.52Z"
        endDate:
          type: string
          format: date-time
          description: Дата закрытия, дата завершения работы над пакетом
          example: "2024-05-28T12:20:50.52Z"
        diagnostics:
          type: array
          items:
            $ref: '#/components/schemas/Diagnosis'
        isShootingRequired:
          type: boolean
          description: Требуется съемка, отмечает приемщик
        isExaminationHeliumRequired:
          type: boolean
          description: Требуется измерение Хелиум, отмечает диагност
        isEngravingRequired:
          type: boolean
          description: Требуется гравировка, отмечает приемщик
        listOfShooting:
          type: array
          items:
            $ref: '#/components/schemas/Shooting'
        listOfExaminationResultHelium:
          type: array
          items:
            $ref: '#/components/schemas/ExaminationResultHelium'
        listOfEngraving:
          type: array
          items:
            $ref: '#/components/schemas/Engraving'
    PackageWithStones:
      type: object
      description: |- 
        Пакет с камнями
      properties:
        quantityOfStones:
          type: integer
          description: количество камней в пакете, вводит приемщик при регистрации пакета
          example: 10
        stoneWeight:
          type: number
          description: вес камней в пакете в каратах, вводит приемщик при регистрации пакета
          format: float
          minimum: 0.00
          example: 1.50
    PackageWithJewelry:
      type: object
      description: |- 
        Пакет с ювелирным изделием
      properties:
        quantityOfJewelry:
          type: integer
          description: количество изделий в пакете, вводит приемщик при регистрации пакета
          example: 2
        jewelryWeight:
          type: number
          format: float
          example: 10.50
          description: вес ювелирного изделия в граммах, вводит приемщик при регистрации пакета
        jewelryKind:
          type: string
          description: вид изделия, вводит приемщик при регистрации пакета (перечень будет дополняться)
          enum:
            - браслет
            - серьги
            - колье
    Diagnosis:
      type: object
      description: |- 
        Диагностика — совокупность процессов по оценке характеристик драгоценного камня при сертификации.
      properties:
        comment:
          type: string
          description: Комментарий
        diamondDiagnostics:
          $ref: '#/components/schemas/DiamondDiagnostics'
        jewelryDiagnostics:
          $ref: '#/components/schemas/JewelryDiagnostics'
        examinationResultAuroraDiamonds:
          type: array
          items:
            $ref: '#/components/schemas/ExaminationResultAuroraDiamonds'
    DiamondDiagnostics:
      type: object
      description: |- 
        Диагностика камня
      properties:
        type:
          type: string
          description: Вид минерала, вводится диагностом (перечень будет дополняться)
          enum:
            - бриллиант
            - сапфир
            - рубин
    JewelryDiagnostics:
      type: object
      description: |- 
        Диагностика ювелирного изделия
      properties:
        type:
          type: string
          description: Вид металла, вводится диагностом (перечень будет дополняться)
        metalSample:
          type: string
          description: Проба металла, вводится диагностом (перечень будет дополняться)
          enum:
            - "925"
            - "585"
            - "875"
          
    Shooting:
      type: object
      description: |- 
        Съемка
      properties:
        number:
          type: integer
          format: int64
          description: Номер снимка, уникальный, формируется системой
        date:
          type: string
          format: date-time
          description: Дата снимка, дата сохранения снимка
        userId:
          type: object
          description: Идентификатор сотрудника
        url:
          type: string
          description: ссылка на виджет (?)
    ExaminationResultHelium:
      type: object
      description: |- 
        Измерения Хелиум
        Helium Polish	— установка для диагностики. Позволяет получить геометрические характеристики камня.
      properties:
        number:
          type: integer
          format: int64
          description: Номер измерения
        date:
          type: string
          format: date-time
          description: Дата измерения
        userId:
          type: object
          description: Идентификатор сотрудника
        source:
          type: object
          description: Исходный файл измерений
        minimumDiameter:
          type: number
          format: float
          description: Минимальный диаметр, мм
          example: 1.50
          minimum: 0.00
          maximum: 100.00
        maximumDiameter:
          type: number
          format: float
          description: Максимальный диаметр, мм
          example: 1.50
          minimum: 0.00
          maximum: 100.00
        height:
          type: number
          format: float
          description: Общая высота, мм
          example: 1.50
          minimum: 0.00
          maximum: 100.00
        tablePercentage:
          type: number
          format: float
          description: Размер площадки, %
          example: 53.80
          minimum: 0.00
          maximum: 100.00
        crownHeightPercentage:
          type: number
          format: float
          description: Высота короны, %
          example: 45.80
          minimum: 0.00
          maximum: 100.00
        pavilionDepthPercentage:
          type: number
          format: float
          description: Глубина павильона, %
          example: 45.80
          minimum: 0.00
          maximum: 100.00
        girdleThicknessPercentage:
          type: number
          format: float
          description: Высота рундиста, %
          example: 45.80
          minimum: 0.00
          maximum: 100.00
        crownAngle:
          type: number
          format: float
          description: Угол короны, град
          example: 32.50
          minimum: 0.00
          maximum: 90.00
        pavilionAngle:
          type: number
          format: float
          description: Угол павильона, град
          example: 40.75
          minimum: 0.00
          maximum: 90.00
    ExaminationResultGemological:
      type: object
      description: |- 
        Результаты геммологической экспертизы
        Геммолог — специалист по оценке драгоценных камней.
      properties:
        number:
          type: integer
          format: int64
          description: Номер экспертизы
        date:
          type: string
          format: date-time
          description: Дата экспертизы
        userId:
          type: object
          description: Идентификатор сотрудника, выполнившего экспертизу
        comment:
          type: string
          description: Произвольный комментарий геммолога
    ExaminationResultAuroraDiamonds:
      type: object
      description: |- 
        Измерения AuroraDiamonds
        Aurora Diamonds	— установка для диагностики. Позволяет просвечивать бриллианты под разными видами излучения и получать соответствующие изображения.
      properties:
        number:
          type: integer
          format: int64
          description: Номер измерения
        date:
          type: string
          format: date-time
          description: Дата измерения
        userId:
          type: object
          description: Идентификатор сотрудника
        comment:
          type: string
          description: Произвольный комментарий сотрудника
        image:
          type: object
          description: Фото, результат измерения
    Engraving:
      type: object
      description: |- 
        Гравировка — процесс нанесения на драгоценный камень (для бриллиантов наносится на рундист) с помощью специальной лазерной установки последовательности символов. 
        Обычно наносится номер сертификата, но может быть произвольная фраза по желанию Клиента.
      properties:
        number:
          type: integer
          format: int64
          description: Номер гравировки
        date:
          type: string
          format: date-time
          description: Дата гравировки
        engravingText:
          type: string
          description: Текст, который нужно выгравировать 
          example: "SGC-01234567890"
        userId:
          type: object
          description: Идентификатор сотрудника, сделавшего гравировку
    Plotting:
      type: object
      description: |- 
        Плоттинг — процесс нанесения на схематическое изображение камня в двух проекциях маркировки дефектов (включения, пятна, трещины и тд).
