openapi: 3.1.0
info:
  title: Система сертификации драгоценных камней
  description: |-
    Ключевая функциональность представляемая системой:
    - Учет договоров и заявок на сертификацию и сертификационных документов.
    - Сертификация драгоценных камней.
    - Выпуск сертификационных документов на драгоценные камни.
    - Проверка подлинности сертификатов
  version: 0.0.1

components:
  schemas:
    Batch:
      type: object
      description: |- 
        Входящий лот — совокупность камней или ювелирных изделий, пришедших от клиента для проведения сертификации. 
        Входящий лот отражается в Дополнительном соглашении или Заявке. 
        Одна входящий лот – одна заявка или доп.соглашение.
      properties:
        batchNumber:
          type: integer
          format: int64
          description: Номер лота
          examples: [10]
        date:
          type: string
          format: date-time
          description: Дата прихода
        clientId:
          type: integer
          format: int32
          description: Идентификатор клиента
          examples: [198772]
        requestId:
          type: integer
          format: int32
          description: Номер заявки или доп. соглашения
          examples: [34562]
        quantityOfStones:
          type: integer
          format: int32
          description: Количество камней в партии
          examples: [7]
        totalWeight:
          type: number
          format: decimal
          description: Общий вес в партии
          examples: [99.13]
    Package:
      type: object
      description: |-
        Пакет — конверт, содержащий объект сертификации. Является составной частью входящего лота. Может включать:
         - одиночный драгоценный камень
         - партия драгоценных камней
         - ювелирное изделие
      properties:
        packageNumber:
          type: integer
          format: int64
          description: Номер пакета
          examples: [10533]
        certificationType:
          type: object
          description: Система сертификации
        packageType:
          type: object
          description: Тип пакета
        certificate:
          $ref: '#/components/schemas/Certificate'
    Certificate:
      type: object
      description: |- 
        Сертификационный документ	— документ, подтверждающий характеристики драгоценного камня, прошедшего сертификацию.
        Бывает двух видов: Сертификат и Экспертное заключение. 
        Экспертное заключение имеет более низкий статус, чем Сертификат.
      properties:
        type:
          type: object
          description: Тип документа
        number:
          type: integer
          format: int64
          description: Номер документа
        date:
          type: string
          format: date-time
          description: Дата выдачи документа
    Worksheet:
      type: object
      description: |- 
        Рабочий лист — форма, в которую вводятся результаты диагностики (натуральность, форма, цвет, чистота и др.характеристики камня). 
        Лист создается для каждого пакета в партии.
      properties:
        number:
          type: integer
          format: int64
          description: Номер рабочего листа
        type:
          type: object
          description: Статус рабочего листа
        startDate:
          type: string
          format: date-time
          description: Дата передачи в работу
        endDate:
          type: string
          format: date-time
          description: Дата закрытия
    PackageWithStones:
      type: object
      description: |- 
        Пакет с камнями
    PackageWithJewelry:
      type: object
      description: |- 
        Пакет с ювелирным изделием
    Diagnostics:
      type: object
      description: |- 
        Диагностика — совокупность процессов по оценке характеристик драгоценного камня при сертификации.
      properties:
        comment:
          type: string
          description: Комментарий
        diamondDiagnostics:
          $ref: '#/components/schemas/DiamondDiagnostics'
        jewelryDiagnostics:
          $ref: '#/components/schemas/JewelryDiagnostics'
        examinationResultAuroraDiamonds:
          type: array
          items:
            $ref: '#/components/schemas/ExaminationResultAuroraDiamonds'
    DiamondDiagnostics:
      type: object
      description: |- 
        Диагностика камня
      properties:
        type:
          type: object
          description: Вид минерала
    JewelryDiagnostics:
      type: object
      description: |- 
        Диагностика ювелирного изделия
      properties:
        type:
          type: object
          description: Вид металла
        purity:
          type: object
          description: Проба металла
    Shooting:
      type: object
      description: |- 
        Съемка
    ExaminationResultHelium:
      type: object
      description: |- 
        Измерения Хелиум
        Helium Polish	— установка для диагностики. Позволяет получить геометрические характеристики камня.
    ExaminationResultGemological:
      type: object
      description: |- 
        Результаты геммологической экспертизы
        Геммолог — специалист по оценке драгоценных камней.
    ExaminationResultAuroraDiamonds:
      type: object
      description: |- 
        Измерения AuroraDiamonds
        Aurora Diamonds	— установка для диагностики. Позволяет просвечивать бриллианты под разными видами излучения и получать соответствующие изображения.
      properties:
        number:
          type: integer
          format: int64
          description: Номер измерения
        date:
          type: string
          format: date-time
          description: Дата измерения
        userId:
          type: object
          description: Идентификатор сотрудника
        comment:
          type: string
          description: Комментарий
        image:
          type: object
          description: Фото, результат измерения
    Engraving:
      type: object
      description: |- 
        Гравировка — процесс нанесения на драгоценный камень (для бриллиантов наносится на рундист) с помощью специальной лазерной установки последовательности символов. 
        Обычно наносится номер сертификата, но может быть произвольная фраза по желанию Клиента.
    Plotting:
      type: object
      description: |- 
        Плоттинг — процесс нанесения на схематическое изображение камня в двух проекциях маркировки дефектов (включения, пятна, трещины и тд).
